/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/dev.glb -o src/components/Dev.jsx -k -K -r public 
*/

import React, { useRef, useState, useEffect, Suspense } from 'react'
import * as THREE from "three"
import {  useGLTF } from '@react-three/drei'
import { section } from 'framer-motion/client'
import { degToRad } from 'three/src/math/MathUtils.js'
import {  motion } from 'framer-motion-3d'
import screen from '../assets/videos/screen.mp4'
import coding from '../assets/videos/coding3.mp4'
import Loader from './Loader'


export function Dev(props) {
  const { nodes, materials } = useGLTF('/models/dev.glb')
  const { section,avatarScale } = props
  const [scaleChair, setScaleChair] = useState(0)
  const [chairPos, setChairPos] = useState({ x: 3, y: 0, z: -2.5 })
  const [chairRot, setChairRot] = useState({ x: degToRad(0), y: degToRad(-140), z: degToRad(0) })
  const [compPos, setCompPos] = useState({ x: 0, y: 0, z: 0 })
  const [compRot, setCompRot] = useState({ x: degToRad(0), y: degToRad(0), z: degToRad(0) })
  const [screenWidth,setScreenWidth] = useState(window.innerWidth)
  const [video1] = useState(()=>{
    
      const vid = document.createElement('video')
      vid.src = coding
      vid.crossOrigin = "Anonymous"
      vid.loop = true
      vid.muted = true
      vid.play()
    
    return vid
    
    
  })
  const [video2] = useState(()=>{
    
    const vid = document.createElement('video')
    vid.src = screen
    vid.crossOrigin = "Anonymous"
    vid.loop = true
    vid.muted = true
    vid.play()
  
  return vid
  
  
})


  const windowWidth = ()=>{
    console.log(window.innerWidth);
    setScreenWidth(window.innerWidth)
   }

   useEffect(()=>{
    window.addEventListener("resize",windowWidth)
   })

  useEffect(() => {
    if (section === 2) {
      setChairPos({ x:screenWidth<768? 3.5 : 3, y: 0, z:screenWidth<768? -3.4 : -2.5 })
      // setChairRot({ x: degToRad(0), y: degToRad(0), z: degToRad(0) })
      setCompPos({ x:screenWidth<768? 3.4 : 2.9, y: 0, z:screenWidth<768? -2.8 : -2 })
      setCompRot({x: degToRad(0), y: degToRad(-140), z: degToRad(0)})
      setScaleChair(1)
    } else if (section === 1) {
      setChairPos({ x: screenWidth<768? 3.8 : 3, y: 0, z: screenWidth<768? -3.2 : -2.5 })
      // setChairRot({ x: degToRad(0), y: degToRad(-140), z: degToRad(0) })
      setScaleChair(1)
      setCompPos({ x:screenWidth<768?4.3 : 0, y: 0, z: 0 })
      setCompRot({x: degToRad(0), y: degToRad(0), z: degToRad(0)})
    } else if (section === 0) {
      setScaleChair(0)
      setCompRot({x: degToRad(0), y: degToRad(0), z: degToRad(0)})
      setCompPos({ x:screenWidth<768? 4.3 : 0, y: 0, z: 0 })
    }
  }, [section, screenWidth])
  return (
    <group {...props} dispose={null} scale={avatarScale}>
      <group name="Scene" >
        <group name="Empty" position={[-0.229, 2.113, -2.373]} rotation={[Math.PI / 2, 0, 0]} />
        {/* <group name="Armature" position={[-0.016, -0.048, -0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.035}>
          <primitive object={nodes.mixamorig7Hips} />
          <skinnedMesh name="Ch08_Beard" geometry={nodes.Ch08_Beard.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Beard.skeleton} />
          <skinnedMesh name="Ch08_Body" geometry={nodes.Ch08_Body.geometry} material={materials.Ch08_body} skeleton={nodes.Ch08_Body.skeleton} />
          <skinnedMesh name="Ch08_Eyelashes" geometry={nodes.Ch08_Eyelashes.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Eyelashes.skeleton} />
          <skinnedMesh name="Ch08_Hair" geometry={nodes.Ch08_Hair.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Hair.skeleton} />
          <skinnedMesh name="Ch08_Hoodie" geometry={nodes.Ch08_Hoodie.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Hoodie.skeleton} />
          <skinnedMesh name="Ch08_Pants" geometry={nodes.Ch08_Pants.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Pants.skeleton} />
          <skinnedMesh name="Ch08_Sneakers" geometry={nodes.Ch08_Sneakers.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Sneakers.skeleton} />
        </group> */}
        <group name="Particle_View_01" position={[9.51, 0, -9.656]} rotation={[0, -1.571, 0]} scale={0.001} />
        <group name="Particle_View_01001" position={[12.102, 1.729, -8.301]} scale={0.001} />
        <group name="Particle_View_01002" position={[12.102, 4.473, -8.301]} scale={0.001} />
        <group name="Particle_View_01003" position={[12.102, 2.882, -8.301]} scale={0.001} />
        <group name="Workplace_016" position={[4.763, 0.737, 1.369]} rotation={[0, 1.571, 0]} scale={0.001} />

        { 
          // <motion.group   transition={{type:'spring',duration:0.6}}  animate={{scale:scaleChair,rotateX:chairRot.x,rotateY:chairRot.y,rotateZ:chairRot.z}}  position={[chairPos.x, chairPos.y, chairPos.z]}>
          <motion.group   transition={{type:'spring',duration:0.6}}  animate={{scale:scaleChair}}  position={[chairPos.x, chairPos.y, chairPos.z]} rotation={[chairRot.x,chairRot.y,chairRot.z]}>
            <group name="Plane" >
              <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.001']} />
              <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.002']} />
            </group>
            <group name="Plane001" position={[-0.016, -0.048, -0.015]} scale={0.836}>
              <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['Material.001']} />
              <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials['Material.002']} />
            </group>
            <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[-0.016, -0.048, -0.015]} scale={[0.187, 0.104, 0.581]} />
            <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} scale={0.102} />
            <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} scale={[0.086, 0.226, 0.086]} />
            <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, -1.571, 0]} scale={[0.082, 0.082, 0.055]} />
            <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, 0, -Math.PI / 2]} scale={-0.09} />
            <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, 1.222, -Math.PI / 2]} scale={-0.09} />
            <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[-Math.PI, 0.698, Math.PI / 2]} scale={-0.09} />
            <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, -0.698, Math.PI / 2]} scale={-0.09} />
            <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, -1.222, -Math.PI / 2]} scale={-0.09} />
            <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.001']} position={[-0.016, -0.048, -0.015]} scale={0.361} />
            <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, 0, 0.204]} scale={0.126} />
            <mesh name="workplace_1027" geometry={nodes.workplace_1027.geometry} material={materials['Metall 1']} position={[-0.016, -0.048, -0.015]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />

          </motion.group>
        }
        {/* <motion.group position={[compPos.x, compPos.y, compPos.z]} rotation={[compRot.x, compRot.y, compRot.z]} > */}
        <motion.group transition={{type:'spring',duration:1}}  animate={{rotateX:compRot.x,rotateY:compRot.y,rotateZ:compRot.z}}  position={[compPos.x,compPos.y,compPos.z]} >
          <group name="Group086" position={[5.096, 0.695, 2.111]} scale={0.001}>
            <group name="MS_notebooks001" position={[-5112.068, -542.493, -2125.632]} rotation={[Math.PI / 2, 0, 0]} scale={1.944}>
              <mesh name="Mesh291" geometry={nodes.Mesh291.geometry} material={materials.MS_leather_brown_dark} />
              <mesh name="Mesh291_1" geometry={nodes.Mesh291_1.geometry} material={materials.MS_pages} />
              <mesh name="Mesh291_2" geometry={nodes.Mesh291_2.geometry} material={materials.MS_bookmark_mat} />
              <mesh name="Mesh291_3" geometry={nodes.Mesh291_3.geometry} material={materials.MS_nubuk} />
              <mesh name="Mesh291_4" geometry={nodes.Mesh291_4.geometry} material={materials.MS_Leather_black} />
            </group>
            <group name="MS_pen" position={[-5112.068, -542.492, -2125.632]} rotation={[-1.264, 0.537, 1.016]} scale={1.607}>
              <mesh name="Mesh292" geometry={nodes.Mesh292.geometry} material={materials['Minotti_black plastic']} />
              <mesh name="Mesh292_1" geometry={nodes.Mesh292_1.geometry} material={materials.MS_Brass} />
              <mesh name="Mesh292_2" geometry={nodes.Mesh292_2.geometry} material={materials['Minotti black plastic']} />
            </group>
          </group>
          <group name="Workplace_017" position={[-0.016, -0.108, -0.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.003}>
            <mesh name="Mesh008" geometry={nodes.Mesh008.geometry} material={materials.Wood} />
            <mesh name="Mesh008_1" geometry={nodes.Mesh008_1.geometry} material={materials.Polished_metal} />
          </group>
          <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials['Iron Clean']} position={[-0.016, -0.41, -0.21]} rotation={[0, Math.PI / 2, 0]} scale={[0.003, 0.00299, 0.0026]} />
          <group name="Workplace_003" position={[0, 0.379, 0.2]} rotation={[Math.PI, 0, Math.PI]} scale={0.0003}>
            <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials.Panel_01} />
            <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials.Keyboards} />
            <mesh name="Mesh010_2" geometry={nodes.Mesh010_2.geometry} material={materials.rubber} />
            <mesh name="Mesh010_3" geometry={nodes.Mesh010_3.geometry} material={materials.Keyboard_body} />
            <mesh name="Mesh010_4" geometry={nodes.Mesh010_4.geometry} material={materials.Keyboard_side} />
          </group>
          <group name="Workplace_001" position={[-0.66, 0.588, 0.09]} rotation={[Math.PI, 0, Math.PI]} scale={0.003}>
            <mesh name="Mesh011" geometry={nodes.Mesh011.geometry} material={materials.Pad_cover} />
            <mesh name="Mesh011_1" geometry={nodes.Mesh011_1.geometry} material={materials.Pad_side} />
            <mesh name="Mesh011_2" geometry={nodes.Mesh011_2.geometry} material={materials.Plastic} />
            <mesh name="Mesh011_3" geometry={nodes.Mesh011_3.geometry} material={materials.Mouse_light} />
            <mesh name="Mesh011_4" geometry={nodes.Mesh011_4.geometry} material={materials.Chrome} />
            <mesh name="Mesh011_5" geometry={nodes.Mesh011_5.geometry} material={materials.chrome_sa} />
            <mesh name="Mesh011_6" geometry={nodes.Mesh011_6.geometry} material={materials.Mouse_wires} />
            <mesh name="Mesh011_7" geometry={nodes.Mesh011_7.geometry} material={materials.Mouse_wire_cover} />
          </group>

          <group name="Workplace_011" position={[-0.016, -0.048, -0.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.003}>
            <mesh name="Mesh013" geometry={nodes.Mesh013.geometry} material={materials.Black_glass} />
            <mesh name="Mesh013_1" geometry={nodes.Mesh013_1.geometry} material={materials.Wood} />
            <mesh name="Mesh013_2" geometry={nodes.Mesh013_2.geometry} material={materials.Polished_metal} />
            <mesh name="Mesh013_3" geometry={nodes.Mesh013_3.geometry} material={materials.rubber} />
          </group>
          {/* <mesh name="Sphere047" geometry={nodes.Sphere047.geometry} material={materials['08 - Default']} position={[-45.729, 2.098, -45.835]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} /> */}
          <group position={[0.5, -1.51, -1.2]} scale={[1.8, 1.6, 2]}>
            <mesh name="Object174069016" geometry={nodes.Object174069016.geometry} material={materials['19 - CoronaMtl']} position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, 0, Math.PI]} scale={0.003} >
              {/* <planeGeometry args={[3.2,1.9]} /> */}
              <meshStandardMaterial emissive={"black"}>
                <videoTexture attach={"map"} args={section === 2 ?[video1]:[video2]} />
                <videoTexture attach={"emissiveMap"} args={section === 2 ?[video1]:[video2]} />
              </meshStandardMaterial>
            </mesh>
            <group name="Workplace_005" position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, 0, Math.PI]} scale={0.003}>
              <mesh name="Mesh286" geometry={nodes.Mesh286.geometry} material={materials.rubber} />
              <mesh name="Mesh286_1" geometry={nodes.Mesh286_1.geometry} material={materials.glossy_plast} />
              <mesh name="Mesh286_2" geometry={nodes.Mesh286_2.geometry} material={materials.plastic} />
              <mesh name="Mesh286_3" geometry={nodes.Mesh286_3.geometry} material={materials.chrome_sa} />
              <mesh name="Mesh286_4" geometry={nodes.Mesh286_4.geometry} material={materials.Black_glass} />
              <mesh name="Mesh286_5" geometry={nodes.Mesh286_5.geometry} material={materials['12 - Default']} />
            </group>
          </group>
          <group name="Cube012" position={[-0.16, 0.091, -0.015]} rotation={[0, 1.571, 0]} scale={[0.572, 0.518, 0.296]}>
            <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.011']} />
            <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Material.010']} />
            <mesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials['Material.015']} />
            <mesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials['Material.014']} />
            <mesh name="Cube006_4" geometry={nodes.Cube006_4.geometry} material={materials['Material.009']} />
            <mesh name="Cube006_5" geometry={nodes.Cube006_5.geometry} material={materials['Material.017']} />
            <mesh name="Cube006_6" geometry={nodes.Cube006_6.geometry} material={materials['aorus case fans']} />
            <mesh name="Cube006_7" geometry={nodes.Cube006_7.geometry} material={materials['Material.016']} />
            <mesh name="Cube006_8" geometry={nodes.Cube006_8.geometry} material={materials['Material.020']} />
            <mesh name="Cube006_9" geometry={nodes.Cube006_9.geometry} material={materials['Material.018']} />
            <mesh name="Cube006_10" geometry={nodes.Cube006_10.geometry} material={materials['Material.019']} />
            <mesh name="Cube006_11" geometry={nodes.Cube006_11.geometry} material={materials.IOSHIELD} />
            <mesh name="Cube006_12" geometry={nodes.Cube006_12.geometry} material={materials['Material.021']} />
            <mesh name="Cube006_13" geometry={nodes.Cube006_13.geometry} material={materials['Material.022']} />
            <mesh name="Cube006_14" geometry={nodes.Cube006_14.geometry} material={materials.MOBOAORUSORANGETRANS} />
            <mesh name="Cube006_15" geometry={nodes.Cube006_15.geometry} material={materials['Material.023']} />
            <mesh name="Cube006_16" geometry={nodes.Cube006_16.geometry} material={materials['Material.024']} />
            <mesh name="Cube006_17" geometry={nodes.Cube006_17.geometry} material={materials['metal-mesh-500x500']} />
            <mesh name="Cube006_18" geometry={nodes.Cube006_18.geometry} material={materials['Material.008']} />
            <mesh name="Cube006_19" geometry={nodes.Cube006_19.geometry} material={materials['Material.026']} />
            <mesh name="Cube006_20" geometry={nodes.Cube006_20.geometry} material={materials['Material.025']} />
            <mesh name="Cube006_21" geometry={nodes.Cube006_21.geometry} material={materials['Material.027']} />
            <mesh name="Cube006_22" geometry={nodes.Cube006_22.geometry} material={materials['rgb-hdd-cover-aorus-v1']} />
            <mesh name="Cube006_23" geometry={nodes.Cube006_23.geometry} material={materials['maxresdefault (1)']} />
            <mesh name="Cube006_24" geometry={nodes.Cube006_24.geometry} material={materials['NVIDIA LOGO']} />
            <mesh name="Cube006_25" geometry={nodes.Cube006_25.geometry} material={materials.psuback} />
            <mesh name="Cube006_26" geometry={nodes.Cube006_26.geometry} material={materials.usb} />
            <mesh name="Cube006_27" geometry={nodes.Cube006_27.geometry} material={materials['Material.013']} />
            <mesh name="Cube006_28" geometry={nodes.Cube006_28.geometry} material={materials['Material.032']} />
            <mesh name="Cube006_29" geometry={nodes.Cube006_29.geometry} material={materials['Material.034']} />
            <mesh name="Cube006_30" geometry={nodes.Cube006_30.geometry} material={materials['Material.033']} />
            <mesh name="Cube006_31" geometry={nodes.Cube006_31.geometry} material={materials['Material.035']} />
            <mesh name="Cube006_32" geometry={nodes.Cube006_32.geometry} material={materials['Material.040']} />
            <mesh name="Cube006_33" geometry={nodes.Cube006_33.geometry} material={materials['Material.038']} />
            <mesh name="Cube006_34" geometry={nodes.Cube006_34.geometry} material={materials['Material.042']} />
            <mesh name="Cube006_35" geometry={nodes.Cube006_35.geometry} material={materials['Material.041']} />
            <mesh name="Cube006_36" geometry={nodes.Cube006_36.geometry} material={materials['Material.045']} />
            <mesh name="Cube006_37" geometry={nodes.Cube006_37.geometry} material={materials['Material.046']} />
            <mesh name="Cube006_38" geometry={nodes.Cube006_38.geometry} material={materials['Material.047']} />
            <mesh name="Cube006_39" geometry={nodes.Cube006_39.geometry} material={materials['test-aorus-m2-souris-aorus-rgb2']} />
            <mesh name="Cube006_40" geometry={nodes.Cube006_40.geometry} material={materials['Material.048']} />
            <mesh name="Cube006_41" geometry={nodes.Cube006_41.geometry} material={materials['Material.049']} />
            <mesh name="Cube006_42" geometry={nodes.Cube006_42.geometry} material={materials['Material.054']} />
            <mesh name="Cube006_43" geometry={nodes.Cube006_43.geometry} material={materials['Material.061']} />
            <mesh name="Cube006_44" geometry={nodes.Cube006_44.geometry} material={materials['Material.050']} />
            <mesh name="Cube006_45" geometry={nodes.Cube006_45.geometry} material={materials['Material.051']} />
            <mesh name="Cube006_46" geometry={nodes.Cube006_46.geometry} material={materials['Material.052']} />
            <mesh name="Cube006_47" geometry={nodes.Cube006_47.geometry} material={materials['Material.056']} />
            <mesh name="Cube006_48" geometry={nodes.Cube006_48.geometry} material={materials['Material.059']} />
            <mesh name="Cube006_49" geometry={nodes.Cube006_49.geometry} material={materials['Material.058']} />
            <mesh name="Cube006_50" geometry={nodes.Cube006_50.geometry} material={materials['Material.062']} />
            <mesh name="Cube006_51" geometry={nodes.Cube006_51.geometry} material={materials['Material.063']} />
            <mesh name="Cube006_52" geometry={nodes.Cube006_52.geometry} material={materials['aorus logotranspa']} />
            <mesh name="Cube006_53" geometry={nodes.Cube006_53.geometry} material={materials['Material.064']} />
            <mesh name="Cube006_54" geometry={nodes.Cube006_54.geometry} material={materials['Material.065']} />
            <mesh name="Cube006_55" geometry={nodes.Cube006_55.geometry} material={materials['Material.085']} />
            <mesh name="Cube006_56" geometry={nodes.Cube006_56.geometry} material={materials['Material.084']} />
            <mesh name="Cube006_57" geometry={nodes.Cube006_57.geometry} material={materials['Material.086']} />
            <mesh name="Cube006_58" geometry={nodes.Cube006_58.geometry} material={materials['Material.087']} />
            <mesh name="Cube006_59" geometry={nodes.Cube006_59.geometry} material={materials['Material.083']} />
            <mesh name="Cube006_60" geometry={nodes.Cube006_60.geometry} material={materials['Material.088']} />
            <mesh name="Cube006_61" geometry={nodes.Cube006_61.geometry} material={materials['Material.094']} />
            <mesh name="Cube006_62" geometry={nodes.Cube006_62.geometry} material={materials['Material.095']} />
            <mesh name="Cube006_63" geometry={nodes.Cube006_63.geometry} material={materials['Material.096']} />
            <mesh name="Cube006_64" geometry={nodes.Cube006_64.geometry} material={materials['Material.097']} />
            {/* <mesh name="Cube006_65" geometry={nodes.Cube006_65.geometry} material={materials['Material.099']} /> */}
            <mesh name="Cube006_66" geometry={nodes.Cube006_66.geometry} material={materials['Material.100']} />
            <mesh name="Cube006_67" geometry={nodes.Cube006_67.geometry} material={materials['Material.101']} />
            <mesh name="Cube006_68" geometry={nodes.Cube006_68.geometry} material={materials['Material.102']} />
            <mesh name="Cube006_69" geometry={nodes.Cube006_69.geometry} material={materials['Material.104']} />
            {/* <mesh name="Cube006_70" geometry={nodes.Cube006_70.geometry} material={materials['Material.103']} /> */}
            {/* <mesh name="Cube006_71" geometry={nodes.Cube006_71.geometry} material={materials['Material.106']} /> */}
            {/* <mesh name="Cube006_72" geometry={nodes.Cube006_72.geometry} material={materials['Material.105']} /> */}
          </group>
        </motion.group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/dev.glb')
