/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 assets/models/scene1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF,useAnimations,useFBX } from '@react-three/drei'
import {a} from '@react-spring/three'

import DevScene from '../assets/3d/scene1.glb'

const Dev = (props) => {
  const devRef = useRef()
  const { nodes, materials } = useGLTF(DevScene)
  const {animations : typingAnimation} = useFBX('animations/Typing.fbx')
  typingAnimation[0].name = "Typing"

  const {actions} = useAnimations(typingAnimation,devRef)

  useEffect(()=>{
    actions["Typing"].reset().play()
  },[])

  return (
    <a.group {...props} dispose={null}>
      <group position={[-0.016, -0.048, -0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.035}>
        <primitive object={nodes.mixamorig7Hips} />
        <skinnedMesh geometry={nodes.Ch08_Beard.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Beard.skeleton} />
        <skinnedMesh geometry={nodes.Ch08_Body.geometry} material={materials.Ch08_body} skeleton={nodes.Ch08_Body.skeleton} />
        <skinnedMesh geometry={nodes.Ch08_Eyelashes.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Eyelashes.skeleton} />
        <skinnedMesh geometry={nodes.Ch08_Hair.geometry} material={materials.Ch08_hair} skeleton={nodes.Ch08_Hair.skeleton} />
        <skinnedMesh geometry={nodes.Ch08_Hoodie.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Hoodie.skeleton} />
        <skinnedMesh geometry={nodes.Ch08_Pants.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Pants.skeleton} />
        <skinnedMesh geometry={nodes.Ch08_Sneakers.geometry} material={materials.Ch08_body1} skeleton={nodes.Ch08_Sneakers.skeleton} />
      </group>
      <group position={[5.096, 0.695, 2.111]} scale={0.001}>
        <group position={[-5112.068, -742.493, -2125.632]} rotation={[Math.PI / 2, 0, 0]} scale={1.944}>
          <mesh geometry={nodes.Mesh291.geometry} material={materials.MS_leather_brown_dark} />
          <mesh geometry={nodes.Mesh291_1.geometry} material={materials.MS_pages} />
          <mesh geometry={nodes.Mesh291_2.geometry} material={materials.MS_bookmark_mat} />
          <mesh geometry={nodes.Mesh291_3.geometry} material={materials.MS_nubuk} />
          <mesh geometry={nodes.Mesh291_4.geometry} material={materials.MS_Leather_black} />
        </group>
        <group position={[-5112.068, -742.492, -2125.632]} rotation={[-1.264, 0.537, 1.016]} scale={1.607}>
          <mesh geometry={nodes.Mesh292.geometry} material={materials['Minotti_black plastic']} />
          <mesh geometry={nodes.Mesh292_1.geometry} material={materials.MS_Brass} />
          <mesh geometry={nodes.Mesh292_2.geometry} material={materials['Minotti black plastic']} />
        </group>
      </group>
      <group position={[-0.016, -0.048, -0.015]}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.016, -0.048, -0.015]} scale={0.836}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[-0.016, -0.048, -0.015]} scale={[0.187, 0.104, 0.581]} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} scale={0.102} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} scale={[0.086, 0.226, 0.086]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, -1.571, 0]} scale={[0.082, 0.082, 0.055]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, 0, -Math.PI / 2]} scale={-0.09} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, 1.222, -Math.PI / 2]} scale={-0.09} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[-Math.PI, 0.698, Math.PI / 2]} scale={-0.09} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, -0.698, Math.PI / 2]} scale={-0.09} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, -1.222, -Math.PI / 2]} scale={-0.09} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.001']} position={[-0.016, -0.048, -0.015]} scale={0.361} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.003']} position={[-0.016, -0.048, -0.015]} rotation={[0, 0, 0.204]} scale={0.126} />
      <mesh geometry={nodes.workplace_1027.geometry} material={materials['Metall 1']} position={[-0.016, -0.048, -0.015]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <group position={[-0.016, -0.048, -0.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.003}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.Polished_metal} />
      </group>
      <mesh geometry={nodes.Circle002_1.geometry} material={materials['Iron Clean']} position={[-0.016, -0.048, -0.015]} rotation={[0, Math.PI / 2, 0]} scale={0.003} />
      <group position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, 0, Math.PI]} scale={0}>
        <mesh geometry={nodes.Mesh010.geometry} material={materials.Panel_01} />
        <mesh geometry={nodes.Mesh010_1.geometry} material={materials.Keyboards} />
        <mesh geometry={nodes.Mesh010_2.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Mesh010_3.geometry} material={materials.Keyboard_body} />
        <mesh geometry={nodes.Mesh010_4.geometry} material={materials.Keyboard_side} />
      </group>
      <group position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, 0, Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Mesh011.geometry} material={materials.Pad_cover} />
        <mesh geometry={nodes.Mesh011_1.geometry} material={materials.Pad_side} />
        <mesh geometry={nodes.Mesh011_2.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Mesh011_3.geometry} material={materials.Mouse_light} />
        <mesh geometry={nodes.Mesh011_4.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Mesh011_5.geometry} material={materials.chrome_sa} />
        <mesh geometry={nodes.Mesh011_6.geometry} material={materials.Mouse_wires} />
        <mesh geometry={nodes.Mesh011_7.geometry} material={materials.Mouse_wire_cover} />
      </group>
      <group position={[-0.016, -0.048, -0.015]} rotation={[0, 1.484, 0]} scale={0.002}>
        <mesh geometry={nodes.Mesh012.geometry} material={materials.Cup_dark_blue} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={materials.Cup_white} />
      </group>
      <group position={[-0.016, -0.048, -0.015]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.003}>
        <mesh geometry={nodes.Mesh013.geometry} material={materials.Black_glass} />
        <mesh geometry={nodes.Mesh013_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Mesh013_2.geometry} material={materials.Polished_metal} />
        <mesh geometry={nodes.Mesh013_3.geometry} material={materials.rubber} />
      </group>
      <mesh geometry={nodes.Sphere047.geometry} material={materials['08 - Default']} position={[-45.729, 2.098, -45.835]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.Object174069016.geometry} material={materials['19 - CoronaMtl']} position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, 0, Math.PI]} scale={0.003} />
      <group position={[-0.016, -0.048, -0.015]} rotation={[Math.PI, 0, Math.PI]} scale={0.003}>
        <mesh geometry={nodes.Mesh286.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Mesh286_1.geometry} material={materials.glossy_plast} />
        <mesh geometry={nodes.Mesh286_2.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Mesh286_3.geometry} material={materials.chrome_sa} />
        <mesh geometry={nodes.Mesh286_4.geometry} material={materials.Black_glass} />
        <mesh geometry={nodes.Mesh286_5.geometry} material={materials['12 - Default']} />
      </group>
      <group position={[-0.016, -0.048, -0.015]} rotation={[0, 1.571, 0]} scale={[0.572, 0.518, 0.296]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube006_6.geometry} material={materials['aorus case fans']} />
        <mesh geometry={nodes.Cube006_7.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube006_8.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cube006_9.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cube006_10.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube006_11.geometry} material={materials.IOSHIELD} />
        <mesh geometry={nodes.Cube006_12.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube006_13.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cube006_14.geometry} material={materials.MOBOAORUSORANGETRANS} />
        <mesh geometry={nodes.Cube006_15.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube006_16.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube006_17.geometry} material={materials['metal-mesh-500x500']} />
        <mesh geometry={nodes.Cube006_18.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube006_19.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Cube006_20.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube006_21.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube006_22.geometry} material={materials['rgb-hdd-cover-aorus-v1']} />
        <mesh geometry={nodes.Cube006_23.geometry} material={materials['maxresdefault (1)']} />
        <mesh geometry={nodes.Cube006_24.geometry} material={materials['NVIDIA LOGO']} />
        <mesh geometry={nodes.Cube006_25.geometry} material={materials.psuback} />
        <mesh geometry={nodes.Cube006_26.geometry} material={materials.usb} />
        <mesh geometry={nodes.Cube006_27.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube006_28.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Cube006_29.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube006_30.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Cube006_31.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Cube006_32.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Cube006_33.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Cube006_34.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube006_35.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Cube006_36.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube006_37.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cube006_38.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cube006_39.geometry} material={materials['test-aorus-m2-souris-aorus-rgb2']} />
        <mesh geometry={nodes.Cube006_40.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Cube006_41.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube006_42.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Cube006_43.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.Cube006_44.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Cube006_45.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Cube006_46.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Cube006_47.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cube006_48.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Cube006_49.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Cube006_50.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Cube006_51.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Cube006_52.geometry} material={materials['aorus logotranspa']} />
        <mesh geometry={nodes.Cube006_53.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Cube006_54.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Cube006_55.geometry} material={materials['Material.085']} />
        <mesh geometry={nodes.Cube006_56.geometry} material={materials['Material.084']} />
        <mesh geometry={nodes.Cube006_57.geometry} material={materials['Material.086']} />
        <mesh geometry={nodes.Cube006_58.geometry} material={materials['Material.087']} />
        <mesh geometry={nodes.Cube006_59.geometry} material={materials['Material.083']} />
        <mesh geometry={nodes.Cube006_60.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Cube006_61.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Cube006_62.geometry} material={materials['Material.095']} />
        <mesh geometry={nodes.Cube006_63.geometry} material={materials['Material.096']} />
        <mesh geometry={nodes.Cube006_64.geometry} material={materials['Material.097']} />
        <mesh geometry={nodes.Cube006_65.geometry} material={materials['Material.099']} />
        <mesh geometry={nodes.Cube006_66.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Cube006_67.geometry} material={materials['Material.101']} />
        <mesh geometry={nodes.Cube006_68.geometry} material={materials['Material.102']} />
        <mesh geometry={nodes.Cube006_69.geometry} material={materials['Material.104']} />
        <mesh geometry={nodes.Cube006_70.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Cube006_71.geometry} material={materials['Material.106']} />
        <mesh geometry={nodes.Cube006_72.geometry} material={materials['Material.105']} />
      </group>
    </a.group>
  )
}



export default Dev
